-- Active: 1753668261437@@192.168.230.1@3306@devdb
create table archivedChallenges
(
    ID             int auto_increment
        primary key,
    HashedFlag     text                 not null,
    PointsValue    int                  not null,
    challengeTitle text                 null,
    challengeText  text                 null,
    moduleID       int                  null,
    Enabled        tinyint(1) default 1 null,
    category       varchar(255)         null,
    container      tinyint(1)           null,
    dChallengeID   varchar(255)         null,
    projectID      int                  not null,
    Image          text                 null,
    constraint Challenges_RegisteredModules_ID_fk
        foreign key (moduleID) references archivedRegisteredModules (ID)
);

INSERT INTO devdb.archivedChallenges (ID, HashedFlag, PointsValue, challengeTitle, challengeText, moduleID, Enabled, category, container, dChallengeID, projectID, Image) VALUES (1, 'CTF{fOuNdIt}', 25, 'Biolab Security Key', 'The Biolab uses an advanced security system. I have some clue where to find it, how about looking for it <a href="keyword.html" class="text-decoration-none">here</a>?', 46, 1, 'Cryptology', null, null, 1, 'SecurityKey.jpeg');
INSERT INTO devdb.archivedChallenges (ID, HashedFlag, PointsValue, challengeTitle, challengeText, moduleID, Enabled, category, container, dChallengeID, projectID, Image) VALUES (26, 'CTF{BuzzBuzz}', 5, 'Fire Department', 'We have reason to believe the Fire Department is hiding something in the website. <!--CTF{BuzzBuzz}--->', 19, 1, 'Tutorial', null, null, 1, 'FireDept.jpg');
INSERT INTO devdb.archivedChallenges (ID, HashedFlag, PointsValue, challengeTitle, challengeText, moduleID, Enabled, category, container, dChallengeID, projectID, Image) VALUES (28, 'CTF{Shark}', 15, 'Wireshark', 'We believe a module is posting its password in plain text. Can you find it?\\n <a href="Cyber City Wireshark.pcapng" download> Download packet capture</a>', 5, 1, 'Networking', null, null, 1, 'LegoShark.jpeg');
INSERT INTO devdb.archivedChallenges (ID, HashedFlag, PointsValue, challengeTitle, challengeText, moduleID, Enabled, category, container, dChallengeID, projectID, Image) VALUES (38, 'CTF{FoundMe}', 25, 'Criminal Records', 'We have reasons to believe that there are secret encrypted files hidden somewhere in the city. CyberChef may be useful.', 43, 1, 'OSINT', null, null, 1, 'fulcrum.jpg');
INSERT INTO devdb.archivedChallenges (ID, HashedFlag, PointsValue, challengeTitle, challengeText, moduleID, Enabled, category, container, dChallengeID, projectID, Image) VALUES (39, 'CTF{Robust}', 20, 'Guess the Passkey', 'We have an agent working within the biolab. They have been slowly weakening their cyber systems and have reported that the passkey for the firewall is a six letter word. The passkey remains unknown to us, however, every minute an email containing clues to the passkey will be sent to you under >>Data<< on this page. Use the clues to find the passkey. Some of the emails point out how it\'s spelled, while others describe its meaning. Can you guess the passkey?', 44, 1, 'TEST', null, null, 1, 'guessThePasskey.jpg');
INSERT INTO devdb.archivedChallenges (ID, HashedFlag, PointsValue, challengeTitle, challengeText, moduleID, Enabled, category, container, dChallengeID, projectID, Image) VALUES (40, 'CTF{Spin}', 10, 'Ventilation System ', 'During an inspection of the biolab’s exhaust vents, we found a message written on one of the vents. It reads “JAM{Zwpu}”. Can you decipher this?', 45, 1, 'Cryptology', null, null, 1, 'vent.jpeg');
INSERT INTO devdb.archivedChallenges (ID, HashedFlag, PointsValue, challengeTitle, challengeText, moduleID, Enabled, category, container, dChallengeID, projectID, Image) VALUES (51, 'CTF{Reroute}', 50, 'Backup Diesel Generators', 'Their last line of defence is a set of backup generators powering a simplistic refrigeration unit that houses the last of their virus samples. If we can reroute their next shipment of diesel, they will be left with no way to refrigerate the samples, losing them. We\'ve managed to acquire the program that handles Blue Whale Shipping\'s invoice system. By modifying it, send the shipment to \'456 Grimace Shake Rd, Ohio\'.<br>Linux: <a href = "../../../serverFiles/backupDieselGenerators/versions/linux/invoiceScript.zip">Download here</a><br>Windows: <a href = "../../../serverFiles/backupDieselGenerators/versions/windows/invoiceScript-win.zip">Download here</a>', 48, 1, 'Hex', null, null, 1, 'backupDieselGenerators.jpg');
INSERT INTO devdb.archivedChallenges (ID, HashedFlag, PointsValue, challengeTitle, challengeText, moduleID, Enabled, category, container, dChallengeID, projectID, Image) VALUES (52, 'CTF{RestorePower}', 15, 'Intercepted Comms', 'We intercepted up a suspicious file being transferred through their network. It is a singular file with thousands of numbers. We believe this file contains the encryption key they use for their communications. We need you to download this file and locate the key hidden within.<br>The “grep” command may be helpful. Username: "sayer" Password: "Password01" IP Address: 10.177.200.71 Port: 2225 ', 49, 1, 'Networking', null, null, 1, 'grepChallengeLogo.jpeg');
INSERT INTO devdb.archivedChallenges (ID, HashedFlag, PointsValue, challengeTitle, challengeText, moduleID, Enabled, category, container, dChallengeID, projectID, Image) VALUES (53, 'CTF{WaterTime}', 25, 'Financial Tracing', 'We’ve been able to capture one of their recent bank transactions, we need you to search through the capture and find their banking details.<br><a href = "../../../serverFiles/financialTracing/financialTracing.zip">Download packet capture</a>', 50, 1, 'Networking', null, null, 1, 'financialTracing.jpg');
INSERT INTO devdb.archivedChallenges (ID, HashedFlag, PointsValue, challengeTitle, challengeText, moduleID, Enabled, category, container, dChallengeID, projectID, Image) VALUES (54, 'CTF{Answor_Here}', 10, 'scavengerhunt00', 'Rebels we have heard that the TBW has left information lying around. Your job is to find this information and submit it to this form.', 51, 1, 'OSINT', null, null, 1, 'trenchCoatMan.jpg');
INSERT INTO devdb.archivedChallenges (ID, HashedFlag, PointsValue, challengeTitle, challengeText, moduleID, Enabled, category, container, dChallengeID, projectID, Image) VALUES (55, 'CTF{ArduinoUno11}', 10, 'scavengerhunt01', 'Great Job Everyone.  We have reasons to believe they are trying to use other locations but they have decoys', 52, 1, 'OSINT', null, null, 1, 'IncognitoWoman.jpg');
INSERT INTO devdb.archivedChallenges (ID, HashedFlag, PointsValue, challengeTitle, challengeText, moduleID, Enabled, category, container, dChallengeID, projectID, Image) VALUES (56, 'CTF{Order_66}', 10, 'scavengerhunt02', 'I Heard one of those guys talking about hiding something under something really obscure.', 53, 1, 'OSINT', null, null, 1, 'jar-jar.jpg');
INSERT INTO devdb.archivedChallenges (ID, HashedFlag, PointsValue, challengeTitle, challengeText, moduleID, Enabled, category, container, dChallengeID, projectID, Image) VALUES (57, 'CTF{EyesBeyond}', 10, 'Computers Beyond', 'A TBW scientist named Graham has had his password appear in a databreach. Lets see if the SSH password to his machine is the same. Username: "graham" Password: "Password01" IP Address: 10.177.200.71 Port: 2222', 54, 1, 'Tutorial', null, null, 1, 'computersBeyond.jpg');
INSERT INTO devdb.archivedChallenges (ID, HashedFlag, PointsValue, challengeTitle, challengeText, moduleID, Enabled, category, container, dChallengeID, projectID, Image) VALUES (58, 'CTF{Finland}', 50, 'West End', 'We\'ve found the IP address and SSH port of a TBW employee, however we don\'t know his password. Can you brute force it and retrieve any information? Username: "cather" IP Address: 10.177.200.71 Port: 2223', 55, 1, 'Networking', null, null, 1, 'Compass.jpg');
INSERT INTO devdb.archivedChallenges (ID, HashedFlag, PointsValue, challengeTitle, challengeText, moduleID, Enabled, category, container, dChallengeID, projectID, Image) VALUES (59, 'CTF{aud10_an0maly}', 25, 'Audio Anomaly', 'We\'ve retrieved a audio file from within the Biolab, but we don\'t understand what it means. Can you dechipher it? <a href = "../../../serverFiles/audioAnomaly/Image to Sound Spectrum.wav">Download here</a>', 56, 1, 'Cryptology', null, null, 1, 'Waveform.jpeg');
INSERT INTO devdb.archivedChallenges (ID, HashedFlag, PointsValue, challengeTitle, challengeText, moduleID, Enabled, category, container, dChallengeID, projectID, Image) VALUES (60, 'CTF{NickFlor}', 50, 'Curly Maps', 'We\'ve gained access to a TBW employee\'s computer via leaked SSH credentials. From within this machine, can you find any information on any other devices on the network? Username: "traise" Password: "Password01" IP Address: 10.177.200.71 Port: 2224', 57, 1, 'Networking', null, null, 1, 'WorldMap.jpg');
INSERT INTO devdb.archivedChallenges (ID, HashedFlag, PointsValue, challengeTitle, challengeText, moduleID, Enabled, category, container, dChallengeID, projectID, Image) VALUES (61, 'CTF{PhilConners}', 25, 'Groundhog Day', '(-B64)^4: VlZSR1UxSXlWWGhSYlRsb1ZqTm9SVmxxU1RGa1ZuQlpVMjV3YlZVd1NrWlpibXhEVGxkSmVsWlhaR0Z YUm5CeldUSnNRMkl4YkZsWGJYaEtVakZTZDFsWVZrSmFNbEoxVmxNNFBRPT0=', 58, 1, 'Cryptology', null, null, 1, 'Clock.jpg');
INSERT INTO devdb.archivedChallenges (ID, HashedFlag, PointsValue, challengeTitle, challengeText, moduleID, Enabled, category, container, dChallengeID, projectID, Image) VALUES (62, 'CTF{YouFoundIt}', 15, 'Where?', 'I\'ve lost my file! Can you find it? Username: "haydon" Password: "Password01" IP Address: 10.177.200.71 Port: 2226', 59, 1, 'Networking', null, null, 1, 'Nature.png');
INSERT INTO devdb.archivedChallenges (ID, HashedFlag, PointsValue, challengeTitle, challengeText, moduleID, Enabled, category, container, dChallengeID, projectID, Image) VALUES (63, 'CTF{Punxsutawney}', 20, 'Permission Slip', 'We\'ve got access to a machine with some program in it, but I can\'t run it. Can you? Username:"connor" Password: "Password01"', 60, 1, 'Networking', 1, 'chmod', 1, 'permissionSlip.png');
INSERT INTO devdb.archivedChallenges (ID, HashedFlag, PointsValue, challengeTitle, challengeText, moduleID, Enabled, category, container, dChallengeID, projectID, Image) VALUES (64, 'CTF{BadWeather}', 20, 'Face Value', 'We\'ve found a file belonging to TBW. It seems like a program but it doesn\'t do anything. Can you find anything? <a href = "../../../serverFiles/faceValue/faceValue">Download here</a>', 61, 1, 'Hex', null, null, 1, 'computersBeyond.jpg');
INSERT INTO devdb.archivedChallenges (ID, HashedFlag, PointsValue, challengeTitle, challengeText, moduleID, Enabled, category, container, dChallengeID, projectID, Image) VALUES (65, 'CTF{BluntTools}', 10, 'scavengerhunt03', 'We need to clean out the garage.', 62, 1, 'OSINT', null, null, 1, 'computersBeyond.jpg');
INSERT INTO devdb.archivedChallenges (ID, HashedFlag, PointsValue, challengeTitle, challengeText, moduleID, Enabled, category, container, dChallengeID, projectID, Image) VALUES (66, 'CTF{MassDestruction}', 50, 'FourStepCipher', 'We have found a serious flaw in their security and have been able to pull out this V1AUj0AdDBcRDCEmjsmcf2icDC0PHlt=. We also found some form of solution, " Caeser decided to use a shift of 5, The N64 was a gamechanging console, An 1863 cipher with a key of FourStep and another word for a beating with 2 letters infront of it.  ', 63, 0, 'Cryptology', null, null, 1, 'FourStep.jpg');
INSERT INTO devdb.archivedChallenges (ID, HashedFlag, PointsValue, challengeTitle, challengeText, moduleID, Enabled, category, container, dChallengeID, projectID, Image) VALUES (67, 'CTF{NobodyExpectsTheSpanishInquisition}', 50, 'TripleThreat', 'We have reason to believe the TBW are mounting an attack, we are unsure of what means however we have recieved this, E1YWr05xPr9qsBL4pIMojVUKnIMYiUMknZEtYK5etJnqfDFwr259. We have also recieved that this is a key for something BudaPest.', 65, 0, 'Cryptology', null, null, 1, 'Trident.jpg');
INSERT INTO devdb.archivedChallenges (ID, HashedFlag, PointsValue, challengeTitle, challengeText, moduleID, Enabled, category, container, dChallengeID, projectID, Image) VALUES (68, 'CTF{ItsColdOutThereToday}', 15, 'Self, Signed', 'Hey look, my website is secure now! There\'s nothing to see, and nothing to find <a href = "https://10.177.200.71:41001">link here</a>', 66, 1, 'Web', null, null, 1, 'computersBeyond.jpg');
INSERT INTO devdb.archivedChallenges (ID, HashedFlag, PointsValue, challengeTitle, challengeText, moduleID, Enabled, category, container, dChallengeID, projectID, Image) VALUES (69, 'CTF{LastSurprise}', 15, 'Unexpected Revelation', 'We have found something odd on the servers of the TBW one image had this text 58 47 55 7b 4f 7a 68 67 48 66 69 6b 69 72 68 76 7d. Can you solve it ', 67, 1, 'Cryptology', null, null, 1, 'Gun.jpg');
INSERT INTO devdb.archivedChallenges (ID, HashedFlag, PointsValue, challengeTitle, challengeText, moduleID, Enabled, category, container, dChallengeID, projectID, Image) VALUES (70, 'CTF{DontDriveAngry}', 20, 'A Cookie Dilemma', 'Look at this website, it\'s got a real secure way of handling user authentification. <a href = "http://10.177.200.71:41002/index.html">link here</a>', 68, 1, 'Web', null, null, 1, 'computersBeyond.jpg');
INSERT INTO devdb.archivedChallenges (ID, HashedFlag, PointsValue, challengeTitle, challengeText, moduleID, Enabled, category, container, dChallengeID, projectID, Image) VALUES (71, 'CTF{DBR}', 15, 'Battle Royal', 'Download this <a href="https://drive.google.com/file/d/1StOAIiA6iVnYIgzjS5lMSdPeFJfc6kfQ/view" target=”_blank”>Download Here</a>', 69, 0, 'OSINT', null, null, 1, 'computersBeyond.jpg');
INSERT INTO devdb.archivedChallenges (ID, HashedFlag, PointsValue, challengeTitle, challengeText, moduleID, Enabled, category, container, dChallengeID, projectID, Image) VALUES (72, 'CTF{pr1v3sc}', 25, 'Run With Me', 'We found the password to a device, but we can\'t figure out where to go from here. Maybe check the administrator\'s home directory? User: \'overseer\' Pass:\'Password01\'', 70, 1, 'Networking', 1, 'suidChallenge', 1, 'computersBeyond.jpg');
