create table archivedRegisteredModules
(
    ID              int auto_increment
        primary key,
    Location        text not null,
    Module          text not null,
    HashedAPIKey    text not null,
    CurrentOutput   text null,
    Enabled         int  null,
    Image           text null,
    Registered_date text null,
    Category        text null
);

INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (5, 'TrafficLightOne', 'TrafficLight', '$2y$12$gqwdvysUIZJXEXpzaciNFOARMI19TefI6YnOeBS9uu5n9z6FrBrp.', 'chaos', 1, 'LegoShark.jpeg', null, null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (6, 'FireDeptX', 'Temperature', '$2y$10$kmX//QclkEHLRVVbKHSkL.LH1a13F41aqo8gfKPDQQHOaXaM07x5m', '0', 0, 'FireDeptX.jpg', null, null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (7, 'RyanTest1', 'RyanTest13', '$2y$10$6wVqGAQXqexirbCTgtSfzeK1I/J.QzVGIOvva3Hut0h.QOazH77bm', '0', 0, null, null, null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (8, 'OliversDesk', 'Testsensor4', '$2y$10$oqobyrNjnHUO3gqPXsIG9usMDsCCHsqOXJVf6NwAIJaTiJ5x/hxHK', '0', 0, null, null, null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (9, 'TrainTimer', 'LCDTimer', '$2y$10$VLtJ9821hdFOI1AidEBOB.ea1VBcPRxUwW5gHaCZ2CKS4qZZ466Wm', '0', 1, 'TrainLCD.jpg', null, null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (14, 'userAccessTest', 'userAccessTest', '$2y$10$NHNnBMSTrr1L3c2MUFrMM.2ChC1wrS.PquB1Dqw0PtgA3x482GOiC', '0', 1, null, null, null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (17, 'the school ', 'bell', '$2y$10$dHvTVjBpAiuMOnrbavmKA.giG1PdtnTZ1x7K/DLcxCqmQktdjItL2', '0', 1, null, null, null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (19, 'Fire Dept', 'Temperature', '$2y$10$fU3DhhDJGPOZTXlkE.DIr.r5irdq0lLHjGQ8b91D3SAeLxwK1Ig1W', 'Off', 1, 'FireDept.jpg', null, null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (34, 'test', 'test', '$2y$10$LLcRD9.oeASyXVNsGjGbIOZt0BdNxR2AUBqIAn0ieWGMAUpiV7Ssy', '0', 1, null, null, null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (35, 'Fire departmentX', 'ESP32', '$2y$10$eg.W1Rh5Q89YEDfeIRO.8.uVS8Uww7K927Ahp3xJzqW1/MfDv0Ba.', '0', 0, null, null, null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (42, 'restaurant', 'fryer', '$2y$10$77nALxYKMkRunYJDOos5fefyosDIL6gW.M5L2OfcRvvCiV.FkHAMe', '0', 1, null, 'November 07 2023 11:34:39.', null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (43, '446F206F7220646F206E6F742E205468657265206973206E6F20747279', 'Mpuk tl, pm fvb jhu...', '$2y$10$TthyijlmpwQP9aznvUdWsOAqTapcaiZGUy1AApRRU4wFDgdlAbKMO', '4', 1, 'fulcrum.jpg', 'December 04 2023 13:25:17.', null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (44, 'Nuclear_Reactor', 'Nuclear_Reactor', '$2y$10$L9jDVkWnR6EDkY25NuUmGebJEqDP820tQj/nX8cmCDBa7lAKh7b0i', '-43', 1, 'guessThePasskey.jpg', 'March 15 2024 11:17:05.', null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (45, 'Windmill', 'Servo', '$2y$10$qdrVw9Ixghp/uDIMQ2dVc.pvv.JPjvBXpA2mb9g/EPbZpyyUCjVSW', '66', 1, 'vent.jpeg', 'March 15 2024 11:54:54.', null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (46, '16x2 LCD Display', 'Adafruit ESP32 Board', '$2y$10$jnNsrlpDWTE216nDFFcqwuroCr3p0TjUydDBffRLDlK6cEvjBncMK', '70', 1, 'SecurityKey.jpeg', 'April 10 2024 14:04:56.', null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (47, '1', '1', '$2y$10$NQ6.h57gpPgoUWM8ZOZqeO4eIdShk8zvE7ToCw9TYsTyMAjLytQwW', '4', 0, null, 'April 10 2024 14:59:56.', null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (48, 'backupDieselGenerators', 'NULL', '$2y$10$yR8pVw9kfyrsMkJvS8xgEOcUiQDla1cXl9qPA5dMGLoVeBavfq1zC', '0', 1, 'backupDieselGenerators.jpg', 'April 11 2024 15:16:43.', null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (49, 'grepChallenge', 'N/A', '$2y$10$s.lW77NMXPhoeLxbVi2l/.oiJRyuB8lFVpnCL7.cL8C3nl2GYNrl2', '25', 1, 'grepChallengeLogo.jpeg', 'May 06 2024 04:11:48.', null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (50, 'financialTracing', 'Na', '$2y$10$Q29Q0A8bSAeJgcJ41dCkH.4Xe8GbBfYYHAtODR4tDfu8FVBuN7rWG', '4', 1, 'financialTracing.jpg', 'May 10 2024 01:17:08.', null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (51, 'Whiteboard', 'Arduino', '$2y$10$74Wt/aURcmTQdZcHazOPSeX9Mi3tUMnJimtsC2oBQV4rtTUB7S8u2', '3', 1, 'trenchCoatMan.jpg', 'September 18 2024 14:09:47.', null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (52, 'Peter’s Arduino board from year 11', 'Arduino2', '$2y$10$zrtjQf02dXDd3a09K1OhnOyiq0t4UFsWsse7HIcWyLCy6hqJbt0S6', '2', 1, 'IncognitoWoman.jpg', 'September 18 2024 04:56:45.', null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (53, 'duck_Vader', 'esp32', '$2y$10$3IC5Zvv34BhbH14J1pJlkOj3..84UHm8Fhu.jYGb778j7p4Y2i5Ny', '2', 1, 'jar-jar.jpg', 'September 18 2024 15:01:30.', null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (54, 'N/A', 'N/A', '$2y$10$VgnVZfk0F5AYKoU3WA5r2uLbmhI.FwczbTbcSVO/uCPHgcqTcitOu', '28', 1, 'computersBeyond.jpg', 'October 16 2024 04:08:16.', null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (55, 'N/A', 'N/A', 'N/A', '5', 1, 'Compass.jpg', 'October 17 2024 03:38:07', null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (56, 'N/A', 'N/A', 'N/A', '5', 1, 'Waveform.jpeg', 'rn dog', null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (57, 'N/A', 'N/A', 'N/A', '13', 1, 'WorldMap.jpg', 'today', null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (58, 'N/A', 'N/A', 'N/A', '7', 1, 'Clock.jpg', 'Always', null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (59, 'N/A', 'N/A', 'N/A', '10', 1, 'Nature.png', 'rn', null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (60, 'N/A', 'N/A', 'N/A', '3', 1, 'permissionSlip.png', 'today', null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (61, 'N/A', 'N/A', 'N/A', '5', 1, 'computersBeyond.jpg', 'now', null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (62, 'N/A', 'N/A', 'N/A', '4', 1, 'computersBeyond.jpg', 'now', null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (63, 'N/A', 'N/A', 'N/A', '4', 1, 'FourStep.jpg', null, null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (64, 'Nowhere', 'ESP32', '$2y$10$9lFaOkpwiZSFCqpeLnwvQOWL2D6ovElmAawpbs1N394.DQNtV76iS', null, 1, 'FourStep.jpg', 'November 04 2024 14:24:17.', null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (65, 'Nowhere', 'ESP32', 'N/A', '2', 1, 'Trident.jpg', null, null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (66, 'N/A', 'N/A', 'N/A', '6', 1, 'computersBeyond.jpg', 'now', null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (67, 'Computer', 'N/A', 'N/A', '3', 1, 'Gun.jpg', 'Nov 6 2024 9:19', null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (68, 'N/A', 'N/A', 'N/A', '7', 1, 'computersBeyond.jpg', 'now', null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (69, 'N/A', 'N/A', 'N/A', '1', 1, 'computersBeyond.jpg', 'now', null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (70, 'N/A', 'wow', 'N/A', '3', 1, 'computersBeyond.jpg', '', '');
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (71, 'dfvf', '111', '$2y$10$mHiL0ETZg/fn7kzIaqg6oO3L4z/pxazb6oaUoqk29EbIXeimi3r0.', null, 1, null, 'November 13 2024 09:30:45.', null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (72, '111', 'aa', '$2y$10$X2QeEu1EHPhesmheyh1t0u9w2OC6iV/2JNVu76iVjhCkSKbKojyQ6', null, 1, null, 'November 13 2024 14:15:36.', null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (74, 'garageDoor', 'servo', '$2y$10$RvQOqsJoP94rqYPIbVZLKuUMxNX6eZp3y6uGAnNq28AavXF2O441O', '6', 1, null, 'April 08 2025 09:40:33.', null);
INSERT INTO devdb.archivedRegisteredModules (ID, Location, Module, HashedAPIKey, CurrentOutput, Enabled, Image, Registered_date, Category) VALUES (75, 'notUsed', 'notUsed', '$2y$10$X7H09LKt4Kom4Lu4mraazeUqsEhqiP2evWi/z5xNSSJTGV.RgJCOO', null, 1, null, 'April 08 2025 09:42:49.', null);
