services:

  bacta-web:
    build: ./web
    container_name: BACTA-php_apache
    ports:
      - "${PORT}:8081"

  sshtest-server:
    build: ./ssh
    container_name: BACTA-ssh
    ports:
      - "${PORT}:22"
    restart: unless-stopped
