services:

  BACTA-web:
    build: .
    image: php:8.2-apache
    container_name: BACTA-php_apache
    ports:
      - "${PORT}:8081"


sshtest-server:
  build: .
  ports:
    - "${PORT}:22" # OUTSIDE:INSIDE
  restart: unless-stopped

